////////////////////////////////////////////////////////////////////////////////////////////
// This is Generated Code
// You should not modify this code as it may be overwritten. Use Partial classes instead
// Generated By Generative Objects  
////////////////////////////////////////////////////////////////////////////////////////////

(function () {
	// GOFileUploader server Component proxy
	forkuapp.Web.Model.Components.GOFileUploaderProxy = function(rootObjectsDataSet) {
		var self = this;

		/// UploadFile Method
		/// Upload the given blob on the remote server
		this.UploadFileRequest = null;
		
		this.isUploadFileBusy = function() {
			return self.UploadFileRequest != null && self.UploadFileRequest.readyState != 4;
		};

		this.UploadFile = function (configuration) {
            if (self.isUploadFileBusy())
                UploadFileRequest.abort();
		
            UploadFileRequest = $.ajax({
                url: configuration.url,
                processData: false,
                contentType: false,
                type: "POST",
                data: configuration.formData,
				success: function (result) {
                    if (configuration.successHandler) {
						configuration.successHandler(result);
					}
				},
                error: function (jqXHR, textStatus, errorThrown) {
                  ApplicationController.errorHandler(jqXHR, errorThrown, configuration.errorHandler, forkuapp.Web.Messages.componentError.replace(/%OPERATION%/g, "GOFileUploader.UploadFile"));
				}
            });
		};	
	};

	if (window.ApplicationSourceHandler)
		window.ApplicationSourceHandler.onSourceLoaded("/Model/Components/GOFileUploaderProxy.js");
} ());
